const SET_CURRENT_ACTION = 'SET_CURRENT_ACTION'
const SET_NODE_RESIZE_MOVE_ATTRIBUTE = 'SET_NODE_RESIZE_MOVE_ATTRIBUTE'
const SET_SVG_OFFSET = 'SET_SVG_OFFSET'
const SET_SCALE_POSITION = 'SET_SCALE_POSITION'
const SET_SVG_CANVAS_STYLE = 'SET_SVG_CANVAS_STYLE'
const SET_SCALE_HOVER_LINE = 'SET_SCALE_HOVER_LINE'
const SET_SCALE_VISIBLE = 'SET_SCALE_VISIBLE'
const SET_PAGE_SELECTION_VISIBLE = 'SET_PAGE_SELECTION_VISIBLE'
const SET_NODE_SELECTION_VISIBLE = 'SET_NODE_SELECTION_VISIBLE'
const SET_LEFT_DRAWER_VISIBLE = 'SET_LEFT_DRAWER_VISIBLE'
//设置划块内元素成组
const SET_BLOCK_ELEMENT_GROUP = 'SET_BLOCK_ELEMENT_GROUP'
//设置跟随菜单
const SET_FOLLOW_MENU_CONFIG = 'SET_FOLLOW_MENU_CONFIG'
export default {
  SET_CURRENT_ACTION,
  SET_NODE_RESIZE_MOVE_ATTRIBUTE,
  SET_SVG_OFFSET,
  SET_SCALE_POSITION,
  SET_SVG_CANVAS_STYLE,
  SET_SCALE_HOVER_LINE,
  SET_SCALE_VISIBLE,
  SET_PAGE_SELECTION_VISIBLE,
  SET_NODE_SELECTION_VISIBLE,
  SET_LEFT_DRAWER_VISIBLE,
  SET_BLOCK_ELEMENT_GROUP,
  SET_FOLLOW_MENU_CONFIG
}
