const SET_CURRENT_ACTION = 'SET_CURRENT_ACTION'
const SET_NODE_RESIZE_MOVE_ATTRIBUTE = 'SET_NODE_RESIZE_MOVE_ATTRIBUTE'
const SET_SVG_OFFSET = 'SET_SVG_OFFSET'
const SET_SCALE_POSITION = 'SET_SCALE_POSITION'
const SET_SVG_CANVAS_STYLE = 'SET_SVG_CANVAS_STYLE'
const SET_SCALE_HOVER_LINE = 'SET_SCALE_HOVER_LINE'
export default {
  SET_CURRENT_ACTION,
  SET_NODE_RESIZE_MOVE_ATTRIBUTE,
  SET_SVG_OFFSET,
  SET_SCALE_POSITION,
  SET_SVG_CANVAS_STYLE,
  SET_SCALE_HOVER_LINE
}
